spring:
  cloud:
    nacos:
      discovery:
        enabled: false
      config:
        enabled: false
        import-check:
          enabled: false
    discovery:
      client:
        simple:
          instances:
            attraction-service:
              - uri: http://127.0.0.1:8092
    sentinel:
      eager: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
