spring:
  cloud:
    discovery:
      client:
        simple:
          instances:
            "attraction-service":
              - uri: http://attraction-service:8092

xxl:
  job:
    enabled: false
